version : "3"

services :
#  web_app_backend:
#    container_name: ada_web_app_backend_container
#    build:
#      context: './ada-core'
#    ports:
#      - "18080:8080"
#    networks:
#      - event-app-db-network
#    restart: unless-stopped
#
#  web_app_frontend:
#    container_name: ada_web_app_frontend_container
#    build:
#      context: './ada-ui'
#    ports:
#      - "80:80"
#    networks:
#      - event-app-db-network
#    restart: unless-stopped

  db_dev:
    container_name: postgres_dev_container
    image: postgres
    environment:
      POSTGRES_USER: "naum97"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "partali-app"
      PGDATA: /data/postgres
    ports:
      - "15432:5432"
    volumes:
      - pgvol_dev:/data/postgresql
    networks:
      - partali-app-db-network
    restart: unless-stopped

  pgadmin :
    container_name: pgadmin_container
    image : dpage/pgadmin4
    environment :
      PGADMIN_DEFAULT_EMAIL : "naum97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD : "1234"
    volumes:
      - pgadminvol:/root/.pgadmin
    ports :
      - "15050:80"
    networks :
      - partali-app-db-network
    restart: unless-stopped

networks :
  partali-app-db-network :
    driver : bridge

volumes:
  pgvol_dev:
  pgvol_test:
  pgadminvol: